export {default as Home} from './home/Home'
export {default as Navbar} from './navbar/Navbar'
export {default as Shop} from './shop/Shop'
export { default as Product } from './shop/Product'
export {default as ProductDetails} from './shop/productDetails'
export {default as Cart} from './cart/Cart'
// export {default as CartContext} from './cart/CartContext'
  export { default as Reviews } from './reviews/Reviews'
 export { default as Contact } from './contact/Contact'
